name: text-width-estimation
channels:
  - conda-forge
  - jetbrains
dependencies:
  - python=3.8
  - Faker
  - jupyter
  - numpy
  - pandas
  - pip
  - scikit-learn
  - svgwrite
  - wxPython
  - pip:
    - lets-plot